import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "bhajan-aadinath-nirala",
    video_title: "Shree Aadinath Se Nirala | श्री आदिनाथ से निराला | फागुन फेरी 2026 Jain Stavan || Pintu Swami",
    video_description: "A beautiful devotional Jain Stavan edit for Pintu Swami. Designed with smooth transitions, serene color grading, and dynamic typography to evoke deep spiritual emotion during the Fagun Feri festival.",
    tags: ["Stavan", "Devotional", "Pintu Swami", "Color Grading"],
    cover_image: "https://img.youtube.com/vi/nt-SpCoL4F4/hqdefault.jpg",
    video_link: "https://youtu.be/nt-SpCoL4F4",
    category: ["Devotional", "Music Video", "Events"],
    publish_date: "2026-02-15",
    client_name: "Pintu Swami Official",
    client_image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "6:44",
    software_used: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    client_feedback: "The video perfectly captures the serene and divine energy of the Stavan. Excellent work on the pacing and visual flow!",
    project_images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "bhajan-tere-ahsan",
    video_title: "Tere Ahsan Ka Badla Chukaya Ja Nahi Sakta || Singer - Pintu Swami",
    video_description: "Cinematic video edit for the soulful bhajan by Pintu Swami. Features seamless visual storytelling, warm tones, and high-quality audio synchronization to create a deeply moving experience.",
    tags: ["Bhajan", "Devotional", "Pintu Swami", "Cinematic"],
    cover_image: "https://img.youtube.com/vi/vnLXiLKOYB4/hqdefault.jpg",
    video_link: "https://youtu.be/vnLXiLKOYB4",
    category: ["Devotional", "Music Video"],
    publish_date: "2026-03-01",
    client_name: "Pintu Swami Official",
    client_image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "5:18",
    software_used: ["Premiere Pro", "DaVinci Resolve"],
    client_feedback: "A beautifully edited video that elevates the emotions of the bhajan. The color grading and scene selections are outstanding.",
    project_images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "bhajan-diwano-toli",
    video_title: "Diwano Ki Toli Aayi hai Mandoli | दीवानों की टोली आई है मांडोली | Pintu Swami (Siddharth Daga)",
    video_description: "A high-energy, vibrant event edit for Pintu Swami's live performance. Focuses on capturing the crowd's enthusiasm, rhythmic movements, and the celebratory atmosphere of Mandoli with fast cuts and synchronized beats.",
    tags: ["Live Concert", "Devotional", "Pintu Swami", "Event Video"],
    cover_image: "https://img.youtube.com/vi/9hRxP-ZpsOU/hqdefault.jpg",
    video_link: "https://youtu.be/9hRxP-ZpsOU",
    category: ["Devotional", "Events"],
    publish_date: "2026-03-10",
    client_name: "Pintu Swami Official",
    client_image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "7:32",
    software_used: ["Premiere Pro", "After Effects", "Color Grading"],
    client_feedback: "The pacing is incredible! It feels like you are right there in the crowd. Thank you for capturing the energy so perfectly.",
    project_images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "bhajan-mandoli-melo",
    video_title: "Mandoli Melo Aay Gyo || माँडोली मेलो आय ग्यो | Pintu Swami (Siddharth Daga)",
    video_description: "Celebratory traditional music video featuring rich Rajasthani cultural themes, energetic choreography, and dynamic color grading that highlights the joy of the Mandoli fair.",
    tags: ["Mela", "Devotional", "Pintu Swami", "Culture"],
    cover_image: "https://img.youtube.com/vi/NqT5dgjZg_o/hqdefault.jpg",
    video_link: "https://youtu.be/NqT5dgjZg_o",
    category: ["Devotional", "Music Video"],
    publish_date: "2026-03-20",
    client_name: "Pintu Swami Official",
    client_image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "6:12",
    software_used: ["Premiere Pro", "After Effects"],
    client_feedback: "Superb storytelling and cultural representation. The edit brings out the life and vibrancy of the festival.",
    project_images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "bhajan-jagmagta-taarla",
    video_title: "JAGMAGTA TAARLA NU DERASAR | POSH DASHAM 2025 | Pintu Swami | New Bhajan",
    video_description: "A cinematic release celebrating the sacred Posh Dasham festival. Designed with soft, glowing visual aesthetics, slow-motion transitions, and premium lighting effects to match the starlight theme of the bhajan.",
    tags: ["Posh Dasham", "Devotional", "Pintu Swami", "Cinematic"],
    cover_image: "https://img.youtube.com/vi/ZF9K_OV99xs/hqdefault.jpg",
    video_link: "https://youtu.be/ZF9K_OV99xs",
    category: ["Devotional", "Music Video"],
    publish_date: "2025-12-25",
    client_name: "Pintu Swami Official",
    client_image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "8:05",
    software_used: ["Premiere Pro", "DaVinci Resolve", "After Effects"],
    client_feedback: "Stunning visual work! The lighting effects and transitions perfectly complement the 'Taarla' (stars) theme.",
    project_images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "bhajan-chintamani-shankheshwar",
    video_title: "चिन्तामणि म्हारी चिंताचूर शंखेश्वर दादा | LIVE BHAJAN | SINGER PINTU SWAMI (Siddharth Daga)",
    video_description: "An emotional and moving live bhajan performance edit. Focused on capturing the spiritual devotion, facial expressions of the singer, and the peaceful ambiance of the live audience.",
    tags: ["Live Bhajan", "Devotional", "Pintu Swami", "Events"],
    cover_image: "https://img.youtube.com/vi/UwdvPcFHgto/hqdefault.jpg",
    video_link: "https://youtu.be/UwdvPcFHgto",
    category: ["Devotional", "Events"],
    publish_date: "2026-01-15",
    client_name: "Pintu Swami Official",
    client_image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "9:40",
    software_used: ["Premiere Pro", "Color Grading"],
    client_feedback: "Very soulful editing. The transitions are subtle and keep the focus entirely on the spiritual experience.",
    project_images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "business-entrepreneur-unfiltered",
    video_title: "Entrepreneur Life Unfiltered | Narad Sahu",
    video_description: "A premium podcast/interview edit for business coach Narad Sahu. Features sharp multi-camera cuts, high-fidelity sound design, and clean lower-thirds to maximize engagement and retain audience focus.",
    tags: ["Podcast", "Business", "Talking Head", "Narad Sahu"],
    cover_image: "GUK7eiWGpwE",
    video_link: "https://youtu.be/GUK7eiWGpwE",
    category: ["Talking Head", "Podcast"],
    publish_date: "2026-04-05",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "15:20",
    software_used: ["Premiere Pro", "After Effects", "Adobe Audition"],
    client_feedback: "Excellent multi-cam pacing! Satyam knows exactly when to cut to keep the conversation engaging.",
    project_images: [
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "business-reprogram-mind",
    video_title: "Reprogram Your Mind 2026: Think Big, Build Big, Become Rich",
    video_description: "An educational explainer/motivation video designed to inspire viewers. Rich in stock footage, text overlays, smooth zoom transitions, and strong voiceover sync.",
    tags: ["Motivation", "Business", "Self Improvement", "Explainer"],
    cover_image: "i_QDvL8TpG8",
    video_link: "https://youtu.be/i_QDvL8TpG8",
    category: ["Talking Head", "Explainer"],
    publish_date: "2026-01-10",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "12:45",
    software_used: ["Premiere Pro", "After Effects", "Photoshop"],
    client_feedback: "The pacing is great, and the typography and visual overlays really hammer the concepts home.",
    project_images: [
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "business-people-fail",
    video_title: "Why do 90% of people fail in business?",
    video_description: "High-impact business discussion looking into market failures and success patterns. Styled with attention-grabbing text callouts, smooth b-roll integration, and high-retention editing techniques.",
    tags: ["Business", "Talking Head", "Explainer", "Retention"],
    cover_image: "eqfyEWTUpz4",
    video_link: "https://youtu.be/eqfyEWTUpz4",
    category: ["Talking Head", "Explainer"],
    publish_date: "2026-02-28",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "10:15",
    software_used: ["Premiere Pro", "After Effects"],
    client_feedback: "Fantastic edit. Pacing is sharp, and the retention metrics on this video have been phenomenal.",
    project_images: [
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&q=80&w=800&h=450"
    ]
  },
  {
    id: "reel-DQTgF09Enlj",
    video_title: "Risk is the Bridge to Success",
    video_description: "Risk is the bridge between where you are and where you want to be. Cross it. 💥",
    tags: ["Reels", "Motivation", "Success", "Elon Musk"],
    cover_image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DQTgF09Enlj/",
    category: ["Reels", "Shorts"],
    publish_date: "2026-03-05",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:45",
    software_used: ["Premiere Pro", "After Effects"],
    client_feedback: "Absolute viral material! The pacing and the sound effects are perfect.",
    project_images: []
  },
  {
    id: "reel-DP8CgLGEta_",
    video_title: "The Ratan Tata Comeback Story",
    video_description: "They once rejected Late Sir Ratan Tata. Years later, he bought their company.",
    tags: ["Reels", "Business Lesson", "Ratan Tata", "Success"],
    cover_image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DP8CgLGEta_/",
    category: ["Reels", "Commercial"],
    publish_date: "2026-01-28",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:30",
    software_used: ["Premiere Pro", "After Effects", "Color Grading"],
    client_feedback: "Stunning product showcase! The speed ramps are incredibly smooth.",
    project_images: []
  },
  {
    id: "reel-DQyN2mjiA6L",
    video_title: "Punjab Day-2 Live Experience",
    video_description: "For deeper learning & real implementation — join the Punjab Day-2 live experience. Founder of SMB, Narad Sahu LIVE in Amritsar City.",
    tags: ["Reels", "Live Event", "Punjab", "Business Coach"],
    cover_image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DQyN2mjiA6L/",
    category: ["Reels", "Podcast", "Shorts"],
    publish_date: "2026-03-25",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:50",
    software_used: ["Premiere Pro", "After Effects"],
    client_feedback: "Captured the best part of our episode beautifully. Engagement on this reel has been massive!",
    project_images: []
  },
  {
    id: "reel-DRbnF1pEog6",
    video_title: "Team Building & Skill Upgrade Mindset",
    video_description: "Better team banani hai? Mindset aur skill dono upgrade karo. 🤝",
    tags: ["Reels", "Team Building", "Leadership", "Growth Mindset"],
    cover_image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DRbnF1pEog6/",
    category: ["Reels", "Shorts"],
    publish_date: "2026-04-12",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:15",
    software_used: ["DaVinci Resolve", "Premiere Pro"],
    client_feedback: "Exactly the vibe we wanted! Beautiful grading and pacing.",
    project_images: []
  },
  {
    id: "reel-DRgXZ-_iFbo",
    video_title: "Narad Sahu Live Session",
    video_description: "An exclusive business training session by coach Narad Sahu live on stage sharing key success paradigms.",
    tags: ["Reels", "Business Coaching", "Event Video", "Live Presentation"],
    cover_image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DRgXZ-_iFbo/",
    category: ["Reels", "Brand Content"],
    publish_date: "2026-04-20",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:40",
    software_used: ["Premiere Pro", "After Effects"],
    client_feedback: "Very professional and polished. It matches our brand identity perfectly.",
    project_images: []
  },
  {
    id: "reel-DSB3u6OiLqE",
    video_title: "Success Ka Raaz: Direction Not Degree",
    video_description: "Success ka raaz degree nahi… direction hai! History sirf batati hai ki kisne kya banaya, Direction batati hai ki aap kahaan tak jaa sakte ho.",
    tags: ["Reels", "Tech", "Explainer", "Success Mindset"],
    cover_image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DSB3u6OiLqE/",
    category: ["Reels", "Explainer"],
    publish_date: "2026-05-02",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:55",
    software_used: ["Premiere Pro", "After Effects"],
    client_feedback: "Simplified a complex feature inside 60 seconds perfectly! The visual aids are brilliant.",
    project_images: []
  },
  {
    id: "reel-DTKLVOoEooQ",
    video_title: "Soch Badlo Toh Sab Badal Jayega",
    video_description: "Soch badlo toh sab badal jayega! ✨ Middle class = Starting point, Middle class mindset = Stopping point. Rich bhi middle class se aaye hain, fark sirf soch ka hai!",
    tags: ["Reels", "Motivation", "Mindset Shift", "Success"],
    cover_image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DTKLVOoEooQ/",
    category: ["Reels", "Commercial"],
    publish_date: "2026-05-18",
    client_name: "Narad Sahu",
    client_image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:35",
    software_used: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    client_feedback: "The energy in this edit is unmatched. The beat sync is absolute perfection!",
    project_images: []
  },
  {
    id: "reel-DTCS7HMCRYy",
    video_title: "Decoding 2026 for You",
    video_description: "Decoding 2026 for you! ✨ Learn about numerology guides, life paths, and what the year has in store.",
    tags: ["Reels", "Numerology", "Transitions", "2026 Guide"],
    cover_image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=800&h=1400",
    video_link: "https://www.instagram.com/reel/DTCS7HMCRYy/",
    category: ["Reels", "Shorts"],
    publish_date: "2026-05-25",
    client_name: "Pranjal R Munndra",
    client_image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150&h=150",
    duration: "0:45",
    software_used: ["Premiere Pro", "DaVinci Resolve"],
    client_feedback: "A sensory masterpiece! The transitions are so seamless they feel like magic.",
    project_images: []
  }
];
